Adding Travis-Ci Support For Arm64
astropy/ci-helpers pull request #434
Opened 2020-01-06 10:33 UTC by ossdev07

Added support for ARM64 in Travis-CI.
Changes done in setup_conda_linux.sh and setup_dependencies_common.sh files.

2020-01-17 04:28 UTC, ossdev07 commented
Ping @bsipocz kindly have a look on this PR.

2020-01-17 04:29 UTC, ossdev07 commented
Ping @bsipocz kindly have a look on this commit

2020-03-20 07:00 UTC, ossdev07 commented
hi @bsipocz ,
Can you please have a look at above PR.

2020-03-20 07:42 UTC, bsipocz commented
Hi @ossdev07!

thanks for the PR. Can I ask what package do you plan to support with these additions? Is the CI there relies on conda, or pip, or tox, or something else?

 Before going into the nitty gritty of reviewing it (unfortunately it adds some complexity to the over complicated script, including non negligible repetitions) , it would be nice to see the bigger picture.

2020-03-23 08:54 UTC, ossdev07 commented
Hi @bsipocz, 

Thanks for the reply.

These additions are required for below packages :
i) pytest-arraydiff
ii) pytest remotedata
iii) astropy 

These 3 packages are using ci-helpers package for the conda environment setup and dependencies installation in Travis. 
There are some repetitions of permission as these are required by the archiconda package for its successful execution.

2020-04-02 13:07 UTC, ossdev07 commented
Ping @bsipocz
 kindly have a look on this commit

2020-04-02 16:53 UTC, bsipocz commented
@ossdev07 - thanks again for the PR.  Unfortunately, as I tried to say above, this doesn't really follow the logic we tried to do before, rather adds extra complexity. I don't have enough bandwith atm to do a thorough review, or reimplementation. Given you say this is motivated by the needs of astropy related packages, it definitely puts the feature to the backburner for me, as I know we are not bottlenecked in astropy by ci-helpers lack of arm support.

2020-04-22 05:42 UTC, ossdev07 commented
Hi @bsipocz

I have added another commit for replacing **archiconda** with **miniforge** which leads to the **removal of all the permission issues** now and the code has the **minimal changes** with the master branch. Kindly go through our commit and let me know if any further changes are required.

2020-05-28 07:55 UTC, ossdev07 commented
Hi @bsipocz,

I have rebased and removed redundant code. Please review and share your opinion.

2020-06-16 05:14 UTC, ossdev07 commented
@bsipocz kindly have a look on this commit and let us know if any changes required.

2020-09-21 04:34 UTC, odidev commented
@bsipocz could you please have a look at this PR and let me know if any changes required.

2020-10-26 14:03 UTC, astrofrog requested changes
Thanks for simplifying this! I think this looks a lot more manageable and some of the changes can be simplified further. Can you also rebase?

2020-10-26 14:03 UTC, astrofrog commented on travis/setup_conda_linux.sh
> +source activate base
Why is this change needed? I thought conda activate was The New Way :tm:?

2020-10-26 14:03 UTC, astrofrog commented on travis/setup_conda_linux.sh
> -
Revert this change

2020-10-26 14:03 UTC, astrofrog commented on travis/setup_dependencies_common.sh
> +                CONDA_DEPENDENCIES=${CONDA_DEPENDENCIES}" nomkl"
Revert since just a whitespace fix

2020-10-26 14:03 UTC, astrofrog commented on travis/setup_dependencies_common.sh
> +if [ `uname -m` = aarch64]; then
Add this as an or (||) clause below instead of having a separate if statement

2020-10-26 14:03 UTC, astrofrog commented on travis/setup_dependencies_common.sh
> +if [ `uname -m` = aarch64]; then
Also use ``TRAVIS_CPU_ARCH`` instead of uname,

2020-10-26 14:03 UTC, astrofrog commented on travis/setup_dependencies_common.sh
> +    if [ `uname -m` = 'aarch64' ]; then
Use TRAVIS_CPU_ARCH

2020-10-26 14:03 UTC, astrofrog commented on travis/setup_conda_linux.sh
> +fi
Also use TRAVIS_CPU_ARCH

2020-11-18 14:49 UTC, pllim commented
Due to recent developments, we have decided not to accept this. Sorry for any inconvenience caused!

Please see https://groups.google.com/g/astropy-dev/c/45frnTEAX-U and astropy/astropy#11045

2020-11-18 14:49 UTC, closed without merging